FirstName:  Lee
LastName:   Taylor
MiddleName: J
Company:    Burning Buttons
Title: Golang Developer
Note: Golang the best.
Email:
  Personal: email_Personal@example.com
  Business: email_Business@example.com
HomeAddr:
  Street: "Marshal Zhukov Street 21 5th floor"
  City: "Omsk"
  State: "Omskaya oblast"
  Country: "Russia"
  ZipCode: "644024"
  CountryCode: "RU"
  Type: "HOME"
  Preferenced: n
WorkAddr:
  Street: "Marshal Zhukov Street 21 5th floor"
  City: "Omsk"
  State: "Omskaya oblast"
  Country: "Russia"
  ZipCode: "644024"
  CountryCode: "RU"
  Type: "WORK"
  Preferenced: y
Website: "https://qwertmax.ru"
Birthday:
  Year: 1900
  Month: 11
  Day: 05
Phone:
  Main: +7000000000
  Home: +7000000000
  Mobile: +7000000000
  Business: +7000000000
